---

- hosts: server
  # Variablen, die für dieses Playbook gelten
  vars:
    - user: tux
    - homedir: "/home/{{ user }}"

  tasks:

    - name: Copy README file
      copy:
        src: files/README.md
        # Variablen müssen IMMER in Anführungszeichen gesetzt werden
        dest: "{{ homedir }}"

    - name: Ensure sudo is installed
      package:
        name: 
          - sudo
        state: present
      become: true

    - name: Install basic packages
      package:
        name: 
          - htop
          - ncdu
          - neovim
        state: latest
      become: true

    - name: Configure SSH Server
      copy:
        src: files/sshd_config
        dest: /etc/ssh/sshd_config
        mode: '0644'
        owner: root
        group: root
      become: true

    - name: Restart SSH Server to apply new configuration
      command: systemctl restart sshd.service
      become: true

    - name: Create test-dir for test-file
      file: 
        path: "{{ homedir }}/test-dir"
        state: directory
        mode: '0755'
        owner: tux
        group: tux

    - name: Create test-file on target system
      command: touch test-file
      args:
        chdir: "{{ homedir }}/test-dir"


