= Docker 

== Architektur

- Docker kann als eine Art von Virtualisierung angesehen werden
- Docker kann benutzt werden, um einzelne Anwendungen plus aller dazu benötigten Abhängigkeiten in einem **Container** bereitzustellen
- Die Anwendung läuft dann ähnlich wie in der Virtualisierung in einer Art **Sandbox**, also abgeschottet vom restlichen Betriebssystem
- Die Anwendungen kommen also nicht mit anderen Anwendungen "in die Quere"
- **Und vor allem:** Wird eine Anwendungen in einem Container kompromitiert, hat dies keine Auswirkungen auf das restliche Betriebssystem


=== Container

- Ein Container ist soetwas wie eine **super-light-weight Virtual Machine**
- Mit einer entscheidenden Einschränkung:
- Es können nur Container für das jeweilige OS bereitgestellt werden


=== Unterschied von Virtualisierung und Containern

==== Virtualisierung

Was wird alles virtualisiert?

- komplette Hardware (über den Hypervisort [Typ I bzw. Typ II]) wie Ein- und Ausgabegeräte, Netzwerkkarten etc.
- ein komplettes OS mit unter anderem:
  - Bootloader
  - Kernel
  - Init System
  - sämtlichen Anwendungen, die (mindestens) in einem OS laufen
  - die zu bereitzustellende Anwendung selbst
  - etc. etc.

Dies sorgt in den meissten Fällen für einen ziemlichen Overhead, also unnütz verbrauchten Resourcen

==== Container

Was wird alles "containerisiert"?

- Dateisystembaum (-> `chroot`)
- die bereitzustellende Anwendunge
- eigenes Netzwerk (Host only)

Container greifen auf den Kernel und die Hardware des Host-Betriebssystems zu

Dadurch benötigen Container extrem wenig Resourcen, sind sehr schnell erstellt und gestartet und einfach übertragbar


=== Vorteile von Containern

- Auf einem System können problemlos **hunderte** Container laufen
- In einem Container läuft _idealerweise_ eine **einzelne** Anwendung
- Komplexere Systeme (z.B. eine Webanwendung mit Datenbank) bestehen dann aus mehreren Containern
- Solche Systeme können durch eine einzelne (einfach aufgebaute) Text-Datei beschrieben werden und mit einem einzelnen Kommando (`docker-compose up`) gestartet werden


=== Images und Container

- Ein Container wird bei Bedarf gebaut und gestartet - aus einem **Image** heraus
- Ein **Image** ist ein Bauplan für eine beliebige Menge an Containern
- Images können z.B. vom **Docker Hub** unter https://hub.docker.com heruntergeladen werden
- Bzw. geschieht das automatisch beim Starten eines Containers, falls das benötigte Image lokal nicht vorhanden ist.

=== Container sind "Wegwerfprodukte"

- Daten werden in Containern nicht gespeichert (sofern wir nicht auf anderem Wege dafür sorgen)
- Docker-Container sind z.B. dafür gedacht, Dinge einmal schnell auszuprobieren
- Docker-Container können aber auch produktiv eingesetzt werden, die Daten müssen dann aber auf dem **Host-System** gespeichert werden (über sog. **Volumes**)


== Grundlegende Kommandos

- `docker run <image>` baut einen Container aus dem Image `<image>` und startet diesen, ist das Image lokal nicht vorhanden, wird es vom Docker Hub heruntergeladen
- `docker pull <image>` lädt `<image>` vom Docker Hub herunter
- `docker run -it <image> /bin/bash` baut einen Container und startet diesen im interaktiven Modus und führt das Kommando `/bin/bash/` aus
- `docker start <container>` Container starten
- `docker stop <container>` Container stoppen
- `docker rm <container>` gestoppten Container entfernen
- `docker logs <container>` Logs des Containers anzeigen
- `docker logs -f <container>` Logs des Containers fortlaufend anzeigen
- `docker image ls` heruntergeladene Images anzeigen 
- `docker run --rm <container> Container automatisch löschen, wenn er beendet wurde
- `docker exec -it <container-id/-name>  /bin/bash` startet den existierenden Container und startet diesen im interaktiven Modus und führt das Kommando `/bin/bash/` aus
- `docker top <container-id/-name>` zeigt alle momentan laufenden Prozesse im Container an

== Ports

Um Zugriff auf einen Container bzw. den Port eines Containers zu erlangen, verbinden wir einen Port des Containers mit einem Port des Host Systems.

- `docker run -p <port-docker-host>:<port-docker-container> <image>` 
- `docker run -p 8888:80 httpd` Port 8888 des Hosts mit dem Port 80 des Containers verbinden

== Volumes 

Mit Volumes bzw. in diesem Fall sog. _Named Volumes_ können Dateien persistent gespeichert werden und so auch einem neu gebauten Container zur Verfügung gestellt werden.

- `docker run -v <verzeichnis-auf-dem-host>:<verzeichnis-im-container`
- `docker run -v ./htdocs:/usr/local/apache2/htdocs` das Verzeichnis `htdocs` auf dem Host wird mit dem Verzeichnis `usr/local/apache2/htdocs` im Container verbunden. Änderungen werden in beide Richtungen übertragen


